all:
	@echo ""

clean:
	rm -f conf.json create_accord_user.sql
	@echo "\t*** CLEAN completed in setup ***"

test:
	@echo "\t*** Triggering TEST in setup ***"
	./dosetup.sh
	@echo "\t*** TEST completed in setup ***"

package:
	@echo "\t*** PACKAGE completed in setup ***"
